#!/bin/bash

### BEGIN INIT INFO
# Provides:             zram-ha
# Required-Start:       $syslog
# Required-Stop:        $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    zram swap and ramdisk
### END INIT INFO

# Raspberry Pi ZRAM script
# For quad core, 1 GB RAM models
# put me in /etc/init.d/zram-ha and make me executable
# then run "sudo update-rc.d zram.sh defaults"

ZRAM_NUM=2
ZRAM_SWAP_MEMLIMIT=128M
ZRAM_SWAP_DISKSIZE=256M
ZRAM_RAMDISK_DIR=/media/ramdisk
ZRAM_RAMDISK_MEMLIMIT=128M
ZRAM_RAMDISK_DISKSIZE=256M

modprobe zram num_devices=$ZRAM_NUM

# zram0 - use as swap
echo $ZRAM_SWAP_MEMLIMIT >/sys/devices/virtual/block/zram0/mem_limit
echo $ZRAM_SWAP_DISKSIZE >/sys/devices/virtual/block/zram0/disksize
mkswap /dev/zram0
swapon -p 0 /dev/zram0

# zram1 - use as ramdisk
echo $ZRAM_RAMDISK_MEMLIMIT >/sys/devices/virtual/block/zram1/mem_limit
echo $ZRAM_RAMDISK_DISKSIZE >/sys/devices/virtual/block/zram1/disksize
mkfs.ext2 /dev/zram1
if [ ! -d "$ZRAM_RAMDISK_DIR" ]; then
  mkdir -p "$ZRAM_RAMDISK_DIR"
fi
mount /dev/zram1 "$ZRAM_RAMDISK_DIR"
chmod 777 "$ZRAM_RAMDISK_DIR"

